"use strict";
exports.__esModule = true;
exports.editor = void 0;
var canvas_1 = require("../editor/js/canvas");
var GameEditor_1 = require("../editor/js/GameEditor");
var doc = document;
var canvas = document.createElement('canvas');
var editor = new GameEditor_1.GameEditor();
exports.editor = editor;
document.getElementById("canvasPlace").appendChild(canvas);
var ctx = canvas.getContext("2d");
(0, canvas_1.resize)(editor, ctx);
window.addEventListener('resize', function () { (0, canvas_1.resize)(editor, ctx); });
